# Generated by Django 4.2.6 on 2023-12-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.URLField()),
                ('about', models.CharField(max_length=230)),
                ('runtime', models.CharField(max_length=20)),
                ('seasons', models.CharField(max_length=10)),
                ('movie_url', models.URLField()),
                ('genre', models.ManyToManyField(to='movieshop.genre')),
            ],
        ),
    ]
